"""The controls that stand between a web page and a shell on this machine.

Hitchrail spawns the agent with its permission prompts disabled, which is
what `claude_ipc.launch_argv` builds and the only place the flags are named.
Anyone who can drive this API can therefore run arbitrary code as the user who
started it, so each control below is a refusal, and each has a test that
asserts the refusal rather than the success path.

The host allowlist is not optional. CVE-2026-32632 (GHSA-hhcg-r27j-fhv9) hit
Glances, a localhost and LAN monitoring web UI, for exactly this gap: no host
validation, therefore DNS rebinding, therefore an attacker's page reading the
API through the victim's own browser. Fixed in 4.5.2 by adding a host
allowlist. Hitchrail has the same shape and a worse blast radius, because it
starts processes rather than reporting on them.
"""

from __future__ import annotations

import secrets
from urllib.parse import parse_qsl, urlencode

from starlette.middleware import Middleware
from starlette.requests import cookie_parser
from starlette.responses import JSONResponse, RedirectResponse, Response
from starlette.types import ASGIApp, Receive, Scope, Send

from hitchrail.config import Config
from hitchrail.hostnames import normalise_origin

SAFE_METHODS = frozenset({"GET", "HEAD", "OPTIONS"})
# The cookie NAME, not a secret. S105 pattern matches on the word "token".
TOKEN_COOKIE = "hitchrail_token"  # noqa: S105
GRANT_PARAM = "token"

# The ONLY paths reachable without a token, and the list is two long on purpose.
#
# #21 moved the grant into a URL fragment, which is never sent to any server.
# Nothing but JavaScript in the browser can read a fragment, so something has
# to be reachable unauthenticated or the flow cannot start. The alternative
# considered and rejected was serving the app shell on a 401: one URL to paste,
# but every future addition to the shell would inherit the exemption, and the
# link is GENERATED by `banner()` so its length costs nobody anything.
#
# `GET /grant` serves a self contained page with no data on it: no project
# names, no memory figures, no root path, and no reference to an asset route,
# which all stay behind the token. `POST /api/grant` checks the token itself
# and is the only way a cookie gets set from it. Neither reveals whether a
# token is correct except by accepting one.
#
# Adding a third entry here is a change to the security boundary and needs the
# same argument #21 made, not a line in a list.
GRANT_PAGE_PATH = "/grant"
GRANT_API_PATH = "/api/grant"

# Keyed on the TRIPLE, not the path. A path alone exempts every method and both
# scope types, so a `WebSocketRoute("/grant", ...)` or a second method on the
# API route would arrive unauthenticated.
UNAUTHENTICATED: frozenset[tuple[str, str, str]] = frozenset(
    {
        ("http", "GET", GRANT_PAGE_PATH),
        # HEAD comes with GET: Starlette adds it to every route that has one, so
        # the router serves `HEAD /grant` and a guard refusing it would name a
        # different route from the one that runs. `/api/grant` is POST only, so
        # it gets no HEAD for the same reason.
        ("http", "HEAD", GRANT_PAGE_PATH),
        ("http", "POST", GRANT_API_PATH),
    }
)
# Thirty days. Long enough that a phone is not re-granted every session, short
# enough that a device left behind stops working eventually.
COOKIE_MAX_AGE = 60 * 60 * 24 * 30


def route_path(scope: Scope) -> str:
    """The path the ROUTER matches on: `path` with `root_path` stripped.

    Ours rather than Starlette's because theirs is `starlette._utils`, which
    `starlette.routing` re-exports without declaring, so mypy refuses the
    public spelling and the private one can move in a patch release. A
    conformance test asserts this agrees with theirs, so the duplicate fails
    loudly here rather than quietly in production.
    """
    path: str = scope["path"]
    root_path: str = scope.get("root_path", "")
    if not root_path or not path.startswith(root_path):
        return path
    if path == root_path:
        return ""
    if path[len(root_path)] == "/":
        return path[len(root_path) :]
    return path


def deny(status: int, code: str, message: str) -> JSONResponse:
    """Every refusal uses the envelope the API uses, so a client parses one shape."""
    return JSONResponse({"code": code, "message": message}, status_code=status)


def header_map(scope: Scope) -> dict[str, str]:
    """Lowercased header names, with the decoding rules the whole stack shares.

    latin-1, which is what RFC 7230 says an HTTP header field is and what
    Starlette's own `Headers` uses. It is also the only choice that cannot
    raise: utf-8 strict throws `UnicodeDecodeError` on a header carrying
    latin-1 bytes, and an attacker chooses those bytes, so decoding strictly
    here is an unauthenticated crash rather than a refusal.

    Shared for the RULES above, not to save the decoding. Each of the three
    middlewares calls this on its own, so a request that reaches all three is
    decoded three times; that is a dict comprehension over a handful of
    headers and is not worth caching state on the scope to avoid. What is
    worth sharing is that all three agree on latin-1, on first-wins, and on
    joining Cookie, because a middleware that read a header differently from
    the one beside it is where request smuggling lives.
    """
    headers: dict[str, str] = {}
    for raw_key, raw_value in scope["headers"]:
        key = raw_key.decode("latin-1").lower()
        value = raw_value.decode("latin-1")
        if key == "cookie":
            # RFC 9113 lets an HTTP/2 client split the cookie jar across
            # several Cookie fields, and reverse proxies do it too. Joining
            # them is what the spec says to do; taking one and dropping the
            # rest loses whichever half held our token.
            headers[key] = f"{headers[key]}; {value}" if key in headers else value
        elif key not in headers:
            # First wins, which is what Starlette's Headers.get returns. Taking
            # the last meant this middleware authenticated a request
            # differently from the rest of the stack that reads the same
            # header, and a difference like that is where smuggling lives.
            headers[key] = value
    return headers


def parse_host(raw: str) -> str:
    """A Host header to a bare host: brackets stripped, port removed, lowercased.

    Returns "" for anything malformed, which matches no allowlist entry because
    `Config` filters empty entries out, so an unparseable Host is refused
    rather than guessed at.

    This exists rather than `TrustedHostMiddleware` because that does
    `host.split(":")[0]`, which turns every IPv6 literal into "[":

        Host: localhost:8787       ->  localhost   ->  served
        Host: [::1]:8787           ->  [           ->  400
        Host: [2001:db8::5]:8787   ->  [           ->  400

    so `http://[::1]:8787/` is refused whatever the allowlist holds, and a
    phone on an IPv6 network cannot reach Hitchrail at all.
    """
    value = raw.strip().lower()
    if value.startswith("["):
        end = value.find("]")
        if end == -1:
            return ""
        # Anything after the closing bracket must be a port, or this is junk.
        rest = value[end + 1 :]
        if rest and not rest.startswith(":"):
            return ""
        return value[1:end]
    # A bare `::1` is not a legal Host header, and more than one colon in an
    # unbracketed value means it is not a host and a port either. Refuse both
    # rather than guess which half is the host.
    if value.count(":") > 1:
        return ""
    host = value.split(":")[0]
    # A Host header has no whitespace in it. Smuggling one past a proxy that
    # splits differently is a known trick, so anything containing it is junk.
    if any(c.isspace() for c in host):
        return ""
    # The FQDN root dot, stripped on this side too. `config.normalise_host`
    # strips it on the way in, and a browser at `http://box.lan./` sends it
    # here, so both doors have to agree or the allowlist holds a spelling the
    # header can never equal. Stripping on one side only is worse than on
    # neither, which is how the first attempt at this was reverted.
    return host.rstrip(".")


class HostAllowlistMiddleware:
    """DNS rebinding defence, applied to every route including the event stream.

    No wildcards, deliberately. `Config` already refuses a wildcard entry, so
    honouring one here would implement a feature the layer below rejects, and
    "*" would then mean "allow everything" the way Starlette's does.

    No www redirect either. Answering an unrecognised Host with a redirect
    built from that same Host is the opposite of not trusting it, and it is
    what `TrustedHostMiddleware` does by default.
    """

    def __init__(self, app: ASGIApp, allowed_hosts: frozenset[str]) -> None:
        self.app = app
        self.allowed = frozenset(h.lower() for h in allowed_hosts if h and h != "*")

    async def __call__(self, scope: Scope, receive: Receive, send: Send) -> None:
        if scope["type"] not in ("http", "websocket"):  # pragma: no cover - lifespan
            await self.app(scope, receive, send)
            return

        host = parse_host(header_map(scope).get("host", ""))
        if host not in self.allowed:
            await deny(400, "host_rejected", "unrecognised Host header")(scope, receive, send)
            return
        await self.app(scope, receive, send)


class OriginCheckMiddleware:
    """CSRF control for a same origin JSON API.

    Browsers attach Origin to cross site requests and a rebound attacker cannot
    forge it, so requiring it to name an origin we already serve is sufficient
    here and needs no token round trip.

    Exact origins, not hostnames. Matching on hostname alone would make
    `http://localhost:3000` same origin with an API equivalent to a shell, so
    every other development server on the machine could drive it.

    Safe methods are exempt, and that is deliberate rather than an oversight:
    `EventSource` cannot set request headers, so `/api/events` cannot carry an
    Origin requirement. There is a named test asserting the exemption exists on
    purpose, because otherwise somebody notices the gap, fixes it, and silently
    breaks every live update in the product.
    """

    def __init__(self, app: ASGIApp, allowed_origins: frozenset[str]) -> None:
        self.app = app
        self.allowed = frozenset(normalise_origin(o) for o in allowed_origins)

    async def __call__(self, scope: Scope, receive: Receive, send: Send) -> None:
        if scope["type"] not in ("http", "websocket"):  # pragma: no cover - lifespan
            await self.app(scope, receive, send)
            return
        # A websocket handshake has no method and is never safe: it is a long
        # lived connection, so it is checked rather than waved through. There
        # is no websocket route today, and adding one later must not silently
        # arrive unauthenticated because this middleware only knew about http.
        if scope["type"] == "http" and scope["method"] in SAFE_METHODS:
            await self.app(scope, receive, send)
            return

        origin = header_map(scope).get("origin", "")
        if not origin:
            await deny(403, "origin_missing", "this request needs an Origin header")(
                scope, receive, send
            )
            return
        # Scheme and host are case insensitive per RFC 3986, and some clients
        # append a slash that is not part of an origin. Normalise both rather
        # than turn either into a refusal nobody can explain.
        if normalise_origin(origin) not in self.allowed:
            await deny(403, "origin_rejected", f"origin not allowed: {origin}")(
                scope, receive, send
            )
            return
        await self.app(scope, receive, send)


def token_matches(presented: str, expected: str) -> bool:
    """Constant time, always. `==` on a secret leaks its prefix through timing.

    Compared as BYTES. `compare_digest` on `str` raises TypeError for anything
    non ASCII, and `presented` comes from an attacker supplied header, cookie,
    query value or JSON body, so the str form turned `Authorization: Bearer
    café` into an unauthenticated 500.

    `surrogatepass` on the presented side, and it is the same bug twice. Every
    carrier that predates #21 is latin-1 decoded, so all of them produce a str
    UTF-8 can encode. A JSON body does not: the decoder accepts a lone
    surrogate, which passes an `isinstance` check and then fails to encode. A
    500 where every other input gets 401 is the oracle this function exists not
    to be. `expected` is the operator's own, where an unencodable token is a
    configuration error rather than an attack.
    """
    return secrets.compare_digest(
        presented.encode("utf-8", "surrogatepass"), expected.encode("utf-8")
    )


def _bearer(header: str) -> str:
    """Extract a bearer credential. RFC 7235 auth schemes are case insensitive.

    Exactly one space, and the credential is not trimmed. `Bearer  token` with
    two spaces means the credential is ` token`, which is not the token, and a
    security control has no business deciding the client meant something other
    than what it sent.
    """
    scheme, separator, credential = header.partition(" ")
    if not separator or scheme.lower() != "bearer":
        return ""
    return credential


def _safe_redirect_path(path: str) -> str:
    r"""A path is not automatically a safe redirect target.

    `/\evil.example` survives as `scope["path"]`, and browsers normalise the
    backslash, so a Location built from it leaves the site. `//evil.example` is
    protocol relative and does the same thing more obviously. One client under
    test normalised the second away by itself, which is exactly why this cannot
    be left to the client.
    """
    if not path.startswith("/") or path[1:2] in {"/", "\\"}:
        return "/"
    # ASGI has already percent decoded the path, and RedirectResponse treats
    # `#` and `?` as safe characters, so a `%23` in the request path became a
    # real fragment in the Location and the browser silently dropped
    # everything after it. Verified live: `/p/foo%23bar` redirected to
    # `/p/foo#bar`. Re-encode both rather than trying to guess intent.
    return path.replace("%", "%25").replace("#", "%23").replace("?", "%3F")


def _scrub_grant_param(scope: Scope) -> str | None:
    """Remove the grant token from the scope and RETURN it, keeping the rest.

    Returning it is what lets the scrub happen first. The grant still needs the
    value, and reading it back out of the scope afterwards would mean either
    not scrubbing yet or scrubbing twice.

    uvicorn writes its access line AFTER the app returns and builds it from
    this same dict, so overwriting the value here is what the logger ends up
    printing. That depends on a uvicorn implementation detail rather than on
    anything ASGI guarantees, which is the same dependency `_maybe_grant`
    already carries a warning about.

    latin-1 for the reason `header_map` spells out: an attacker picks these
    bytes, and a strict `.decode()` raises `UnicodeDecodeError` on anything
    over 0x7f, which would be an unauthenticated 500 rather than a refusal.
    """
    raw = scope.get("query_string", b"")
    if not raw or GRANT_PARAM.encode("latin-1") not in raw:
        return None
    params = parse_qsl(raw.decode("latin-1"), keep_blank_values=True)
    offered = next((v for k, v in params if k == GRANT_PARAM), None)
    if offered is None:
        # The name appeared as a substring of some other key or value. Nothing
        # to remove, and re encoding would needlessly rewrite the caller's
        # query string.
        return None
    kept = [(k, v) for k, v in params if k != GRANT_PARAM]
    scope["query_string"] = urlencode(kept).encode("latin-1")
    return str(offered)


class TokenMiddleware:
    """One shared token, over three carriers.

    `EventSource` cannot set request headers, so a token that lives only in
    `Authorization` authenticates every route except the live update stream,
    which is the one the interface exists to use. The cookie is the carrier
    `EventSource` can use; the query grant is how that cookie gets set from a
    link you open on a phone.

    The cookie is `SameSite=Lax`, not `Strict`, and the origin check still runs
    on every mutating request. Either alone would cover the cases we can think
    of, which is why there are two.

    Lax rather than Strict because Strict is withheld on a cross site TOP LEVEL
    navigation, which is exactly the phone flow this exists for: grant the
    cookie once, then later tap a Hitchrail link from a dashboard or a message
    and be answered 401 by a cookie you do hold, which a reload then fixes. Lax
    sends it on a top level GET and still withholds it from a cross site POST,
    and the mutations that matter are behind the origin check regardless.

    It is deliberately not `Secure`. Over plain HTTP on a LAN, a documented and
    supported deployment, a `Secure` cookie is never sent and the tool silently
    stops working. The cleartext exposure is stated as a limitation in the
    README, with a TLS terminating proxy as the remedy.
    """

    def __init__(self, app: ASGIApp, token: str | None) -> None:
        self.app = app
        self.token = token

    async def __call__(self, scope: Scope, receive: Receive, send: Send) -> None:
        if scope["type"] not in ("http", "websocket") or self.token is None:
            await self.app(scope, receive, send)
            return

        # BEFORE the three carrier checks below, not inside `_maybe_grant`.
        #
        # The grant path already scrubbed the token from the scope, but it is
        # only reached when no valid header and no valid cookie were presented
        # AND the method is safe. Three reachable paths therefore still logged
        # the token in cleartext, and the one that matters is ordinary re use
        # of the intended flow: the README's phone link is a link, so a tab
        # restore, the back button or re tapping a bookmark sends the cookie
        # set the first time AND the still present `?token=`, and uvicorn logs
        # the query string.
        #
        # Rewriting the scope for requests that go on to reach the application
        # is deliberate rather than collateral. No route should ever see an
        # auth token as query data, so stripping it centrally also guarantees
        # no future handler can reflect it into a response body or a log of its
        # own. See #20.
        #
        # NOT a complete fix, and it must not be described as one. The README
        # recommends a TLS terminating proxy, and nginx's default combined
        # format logs the query string, so in the recommended deployment the
        # token still lands in the proxy's log whatever we do here. #21 moves
        # the grant into a URL fragment, which is never sent to any server, and
        # is the actual fix.
        offered_grant = _scrub_grant_param(scope)

        # The exemption, and it is a PATH test rather than a content type one.
        # `Accept: text/html` on any 401 would mean the API starts answering a
        # script with HTML the moment somebody sends a browser shaped header.
        #
        # Exact, and after the scrub so an exempt path cannot smuggle a token
        # into the access log. The Origin check still runs on `POST /api/grant`,
        # because it sits inside this middleware and a grant is mutating.
        # `route_path`, not `scope["path"]`: the guard has to name the same
        # route the router will serve, and behind a sub path proxy the
        # unstripped path names a different one. That is the whole argument.
        # Sub path mounting is not a documented deployment and this does not
        # make it one; what it stops is a guard and a router disagreeing about
        # which route a request is for, which is a bug whatever the deployment.
        if (scope["type"], scope.get("method", ""), route_path(scope)) in UNAUTHENTICATED:
            await self.app(scope, receive, send)
            return

        headers = header_map(scope)

        presented = _bearer(headers.get("authorization", ""))
        if presented and token_matches(presented, self.token):
            await self.app(scope, receive, send)
            return

        # cookie_parser, not SimpleCookie: SimpleCookie discards the WHOLE jar
        # when any crumb is malformed, so one bad cookie set by another
        # application on the same host silently stops us authenticating.
        offered = cookie_parser(headers.get("cookie", "")).get(TOKEN_COOKIE)
        if offered is not None and token_matches(offered, self.token):
            await self.app(scope, receive, send)
            return

        # The grant is an HTTP redirect, so it has no meaning for a websocket
        # handshake; such a connection is refused rather than granted.
        if (
            scope["type"] == "http"
            and scope["method"] in SAFE_METHODS
            and await self._maybe_grant(scope, receive, send, offered_grant)
        ):
            return

        await deny(401, "unauthorized", "a valid token is required")(scope, receive, send)

    async def _maybe_grant(
        self, scope: Scope, receive: Receive, send: Send, offered: str | None
    ) -> bool:
        """Trade `?token=` for a cookie, then redirect the token out of the URL.

        Safe methods only. A grant on a mutating request would let a link
        perform an action, which is the shape of the attack the origin check
        exists to stop.

        Returns True when it answered the request.
        """
        assert self.token is not None
        # `offered` was taken by `_scrub_grant_param` before any carrier check
        # ran, and the scope no longer holds it. Re reading it here would mean
        # either scrubbing later, which is the leak #20 is about, or scrubbing
        # twice.
        if offered is None or not token_matches(offered, self.token):
            return False

        # Already scrubbed, so this IS the remaining query string.
        remaining = scope.get("query_string", b"").decode("latin-1")
        path = _safe_redirect_path(scope["path"])
        location = f"{path}?{remaining}" if remaining else path

        # Take the token out of the scope, not only out of the Location.
        #
        # uvicorn writes its access line AFTER the app returns, and it builds
        # that line from this same dict: get_path_with_query_string reads
        # scope["query_string"] at logging time. Redirecting the token out of
        # the address bar therefore did nothing for the server's own log, where
        # every grant landed as `"GET /?token=<the real token>" 303` in
        # cleartext, in a file that gets tailed, shipped and pasted into bug
        # reports. Overwriting the value here is what the logger ends up
        # printing, verified on a live socket by test_live_socket.py.
        #
        # This depends on a uvicorn implementation detail, NOT on anything ASGI
        # guarantees. h11_impl emits the access line inside send() while
        # handling http.response.start, and protocols/utils builds it from the
        # live scope, so a rewrite before `await response(...)` lands in the
        # log. Verified against uvicorn 0.52.4 on a real socket. If that
        # ordering changes, test_the_grant_keeps_the_token_out_of_the_access_log
        # fails, which is the point of pinning it with a live test rather than
        # a unit test. Nothing downstream reads the value: this request is
        # answered here with a 303.
        #
        # This covers the grant path ONLY. A request that already carries a
        # valid cookie or Bearer header returns before reaching this function,
        # so re-opening the same link still logs the token. See #20.
        scope["query_string"] = remaining.encode("latin-1")

        response = RedirectResponse(location, status_code=303)
        set_token_cookie(response, self.token)
        await response(scope, receive, send)
        return True


def set_token_cookie(response: Response, token: str) -> None:
    """One place, because two carriers now set it.

    The query grant redirects and the fragment grant answers a POST, and a
    cookie that differed between them would be a security control with two
    definitions. Not `Secure`, for the reason in `TokenMiddleware`'s docstring:
    over plain HTTP on a LAN, a supported deployment, a `Secure` cookie is never
    sent and the tool silently stops working.
    """
    response.set_cookie(
        TOKEN_COOKIE,
        token,
        httponly=True,
        samesite="lax",
        path="/",
        max_age=COOKIE_MAX_AGE,
    )


def middleware_stack(config: Config) -> list[Middleware]:
    """Order matters, and it is asserted by a test rather than left to habit.

    Starlette applies this list as an onion: the first entry is outermost and
    runs first.

    Host is outermost so a rebound request never reaches anything that could
    leak whether a token is even correct. Token sits before Origin so an
    unauthenticated caller cannot learn which origins this server accepts.
    """
    return [
        Middleware(HostAllowlistMiddleware, allowed_hosts=frozenset(config.allowed_hosts)),
        Middleware(TokenMiddleware, token=config.token),
        Middleware(OriginCheckMiddleware, allowed_origins=config.allowed_origins),
    ]
