"""The controls that stand between a web page and a shell on this machine.

Hitchrail spawns the agent with its permission prompts disabled, which is
what `claude_ipc.launch_argv` builds and the only place the flags are named.
Anyone who can drive this API can therefore run arbitrary code as the user who
started it, so each control below is a refusal, and each has a test that
asserts the refusal rather than the success path.

The host allowlist is not optional. CVE-2026-32632 (GHSA-hhcg-r27j-fhv9) hit
Glances, a localhost and LAN monitoring web UI, for exactly this gap: no host
validation, therefore DNS rebinding, therefore an attacker's page reading the
API through the victim's own browser. Fixed in 4.5.2 by adding a host
allowlist. Hitchrail has the same shape and a worse blast radius, because it
starts processes rather than reporting on them.
"""

from __future__ import annotations

import secrets

from starlette.middleware import Middleware
from starlette.requests import cookie_parser
from starlette.responses import JSONResponse, Response
from starlette.types import ASGIApp, Receive, Scope, Send

from hitchrail.config import Config
from hitchrail.hostnames import normalise_origin

SAFE_METHODS = frozenset({"GET", "HEAD", "OPTIONS"})
# The cookie NAME, not a secret. S105 pattern matches on the word "token".
TOKEN_COOKIE = "hitchrail_token"  # noqa: S105

# The ONLY requests reachable without a token, and the set is small on purpose.
#
# #21 moved the grant into a URL fragment, which is never sent to any server.
# Nothing but JavaScript in the browser can read a fragment, so something has
# to be reachable unauthenticated or the flow cannot start. The alternative
# considered and rejected was serving the app shell on a 401: one URL to paste,
# but every future addition to the shell would inherit the exemption, and the
# link is GENERATED by `banner()` so its length costs nobody anything.
#
# `GET /grant` serves a self contained page with no data on it: no project
# name, no memory figure, no root path, and no asset route, which all stay
# behind the token. `POST /api/grant` checks the token itself. Neither reveals
# whether a token is correct except by accepting one.
#
# Adding an entry here is a change to the security boundary and needs the same
# argument #21 made, not a line in a list. The check NAMES them rather than
# counting them, because this comment once said "two long" above a set of three.
GRANT_PAGE_PATH = "/grant"
GRANT_API_PATH = "/api/grant"

# Keyed on the TRIPLE, not the path. A path alone exempts every method and both
# scope types, so a `WebSocketRoute("/grant", ...)` or a second method on the
# API route would arrive unauthenticated.
UNAUTHENTICATED: frozenset[tuple[str, str, str]] = frozenset(
    {
        ("http", "GET", GRANT_PAGE_PATH),
        # HEAD comes with GET: Starlette adds it to every route that has one, so
        # the router serves `HEAD /grant` and a guard refusing it would name a
        # different route from the one that runs. `/api/grant` is POST only, so
        # it gets no HEAD for the same reason.
        ("http", "HEAD", GRANT_PAGE_PATH),
        ("http", "POST", GRANT_API_PATH),
    }
)
# Thirty days. Long enough that a phone is not re-granted every session, short
# enough that a device left behind stops working eventually.
COOKIE_MAX_AGE = 60 * 60 * 24 * 30


def route_path(scope: Scope) -> str:
    """The path the ROUTER matches on: `path` with `root_path` stripped.

    Ours rather than Starlette's because theirs is `starlette._utils`, which
    `starlette.routing` re-exports without declaring, so mypy refuses the
    public spelling and the private one can move in a patch release. A
    conformance test asserts this agrees with theirs, so the duplicate fails
    loudly here rather than quietly in production.
    """
    path: str = scope["path"]
    root_path: str = scope.get("root_path", "")
    if not root_path or not path.startswith(root_path):
        return path
    if path == root_path:
        return ""
    if path[len(root_path)] == "/":
        return path[len(root_path) :]
    return path


def deny(status: int, code: str, message: str) -> JSONResponse:
    """Every refusal uses the envelope the API uses, so a client parses one shape."""
    return JSONResponse({"code": code, "message": message}, status_code=status)


def header_map(scope: Scope) -> dict[str, str]:
    """Lowercased header names, with the decoding rules the whole stack shares.

    latin-1, which is what RFC 7230 says an HTTP header field is and what
    Starlette's own `Headers` uses. It is also the only choice that cannot
    raise: utf-8 strict throws `UnicodeDecodeError` on a header carrying
    latin-1 bytes, and an attacker chooses those bytes, so decoding strictly
    here is an unauthenticated crash rather than a refusal.

    Shared for the RULES above, not to save the decoding. Each of the three
    middlewares calls this on its own, so a request that reaches all three is
    decoded three times; that is a dict comprehension over a handful of
    headers and is not worth caching state on the scope to avoid. What is
    worth sharing is that all three agree on latin-1, on first-wins, and on
    joining Cookie, because a middleware that read a header differently from
    the one beside it is where request smuggling lives.
    """
    headers: dict[str, str] = {}
    for raw_key, raw_value in scope["headers"]:
        key = raw_key.decode("latin-1").lower()
        value = raw_value.decode("latin-1")
        if key == "cookie":
            # RFC 9113 lets an HTTP/2 client split the cookie jar across
            # several Cookie fields, and reverse proxies do it too. Joining
            # them is what the spec says to do; taking one and dropping the
            # rest loses whichever half held our token.
            headers[key] = f"{headers[key]}; {value}" if key in headers else value
        elif key not in headers:
            # First wins, which is what Starlette's Headers.get returns. Taking
            # the last meant this middleware authenticated a request
            # differently from the rest of the stack that reads the same
            # header, and a difference like that is where smuggling lives.
            headers[key] = value
    return headers


def parse_host(raw: str) -> str:
    """A Host header to a bare host: brackets stripped, port removed, lowercased.

    Returns "" for anything malformed, which matches no allowlist entry because
    `Config` filters empty entries out, so an unparseable Host is refused
    rather than guessed at.

    This exists rather than `TrustedHostMiddleware` because that does
    `host.split(":")[0]`, which turns every IPv6 literal into "[":

        Host: localhost:8787       ->  localhost   ->  served
        Host: [::1]:8787           ->  [           ->  400
        Host: [2001:db8::5]:8787   ->  [           ->  400

    so `http://[::1]:8787/` is refused whatever the allowlist holds, and a
    phone on an IPv6 network cannot reach Hitchrail at all.
    """
    value = raw.strip().lower()
    if value.startswith("["):
        end = value.find("]")
        if end == -1:
            return ""
        # Anything after the closing bracket must be a port, or this is junk.
        rest = value[end + 1 :]
        if rest and not rest.startswith(":"):
            return ""
        return value[1:end]
    # A bare `::1` is not a legal Host header, and more than one colon in an
    # unbracketed value means it is not a host and a port either. Refuse both
    # rather than guess which half is the host.
    if value.count(":") > 1:
        return ""
    host = value.split(":")[0]
    # A Host header has no whitespace in it. Smuggling one past a proxy that
    # splits differently is a known trick, so anything containing it is junk.
    if any(c.isspace() for c in host):
        return ""
    # The FQDN root dot, stripped on this side too. `config.normalise_host`
    # strips it on the way in, and a browser at `http://box.lan./` sends it
    # here, so both doors have to agree or the allowlist holds a spelling the
    # header can never equal. Stripping on one side only is worse than on
    # neither, which is how the first attempt at this was reverted.
    return host.rstrip(".")


class HostAllowlistMiddleware:
    """DNS rebinding defence, applied to every route including the event stream.

    No wildcards, deliberately. `Config` already refuses a wildcard entry, so
    honouring one here would implement a feature the layer below rejects, and
    "*" would then mean "allow everything" the way Starlette's does.

    No www redirect either. Answering an unrecognised Host with a redirect
    built from that same Host is the opposite of not trusting it, and it is
    what `TrustedHostMiddleware` does by default.
    """

    def __init__(self, app: ASGIApp, allowed_hosts: frozenset[str]) -> None:
        self.app = app
        self.allowed = frozenset(h.lower() for h in allowed_hosts if h and h != "*")

    async def __call__(self, scope: Scope, receive: Receive, send: Send) -> None:
        if scope["type"] not in ("http", "websocket"):  # pragma: no cover - lifespan
            await self.app(scope, receive, send)
            return

        host = parse_host(header_map(scope).get("host", ""))
        if host not in self.allowed:
            await deny(400, "host_rejected", "unrecognised Host header")(scope, receive, send)
            return
        await self.app(scope, receive, send)


class OriginCheckMiddleware:
    """CSRF control for a same origin JSON API.

    Browsers attach Origin to cross site requests and a rebound attacker cannot
    forge it, so requiring it to name an origin we already serve is sufficient
    here and needs no token round trip.

    Exact origins, not hostnames. Matching on hostname alone would make
    `http://localhost:3000` same origin with an API equivalent to a shell, so
    every other development server on the machine could drive it.

    Safe methods are exempt, and that is deliberate rather than an oversight:
    `EventSource` cannot set request headers, so `/api/events` cannot carry an
    Origin requirement. There is a named test asserting the exemption exists on
    purpose, because otherwise somebody notices the gap, fixes it, and silently
    breaks every live update in the product.
    """

    def __init__(self, app: ASGIApp, allowed_origins: frozenset[str]) -> None:
        self.app = app
        self.allowed = frozenset(normalise_origin(o) for o in allowed_origins)

    async def __call__(self, scope: Scope, receive: Receive, send: Send) -> None:
        if scope["type"] not in ("http", "websocket"):  # pragma: no cover - lifespan
            await self.app(scope, receive, send)
            return
        # A websocket handshake has no method and is never safe: it is a long
        # lived connection, so it is checked rather than waved through. There
        # is no websocket route today, and adding one later must not silently
        # arrive unauthenticated because this middleware only knew about http.
        if scope["type"] == "http" and scope["method"] in SAFE_METHODS:
            await self.app(scope, receive, send)
            return

        origin = header_map(scope).get("origin", "")
        if not origin:
            await deny(403, "origin_missing", "this request needs an Origin header")(
                scope, receive, send
            )
            return
        # Scheme and host are case insensitive per RFC 3986, and some clients
        # append a slash that is not part of an origin. Normalise both rather
        # than turn either into a refusal nobody can explain.
        if normalise_origin(origin) not in self.allowed:
            await deny(403, "origin_rejected", f"origin not allowed: {origin}")(
                scope, receive, send
            )
            return
        await self.app(scope, receive, send)


def token_matches(presented: str, expected: str) -> bool:
    """Constant time, always. `==` on a secret leaks its prefix through timing.

    Compared as BYTES. `compare_digest` on `str` raises TypeError for anything
    non ASCII, and `presented` comes from an attacker supplied header, cookie,
    query value or JSON body, so the str form turned `Authorization: Bearer
    café` into an unauthenticated 500.

    `surrogatepass` on the presented side, and it is the same bug twice. Every
    carrier that predates #21 is latin-1 decoded, so all of them produce a str
    UTF-8 can encode. A JSON body does not: the decoder accepts a lone
    surrogate, which passes an `isinstance` check and then fails to encode. A
    500 where every other input gets 401 is the oracle this function exists not
    to be. `expected` is the operator's own, where an unencodable token is a
    configuration error rather than an attack.
    """
    return secrets.compare_digest(
        presented.encode("utf-8", "surrogatepass"), expected.encode("utf-8")
    )


def _bearer(header: str) -> str:
    """Extract a bearer credential. RFC 7235 auth schemes are case insensitive.

    Exactly one space, and the credential is not trimmed. `Bearer  token` with
    two spaces means the credential is ` token`, which is not the token, and a
    security control has no business deciding the client meant something other
    than what it sent.
    """
    scheme, separator, credential = header.partition(" ")
    if not separator or scheme.lower() != "bearer":
        return ""
    return credential


class TokenMiddleware:
    """One shared token, over two carriers.

    `EventSource` cannot set request headers, so a token that lives only in
    `Authorization` authenticates every route except the live update stream,
    which is the one the interface exists to use. The cookie is the carrier
    `EventSource` can use, and `POST /api/grant` is how it gets set from a link
    you open on a phone.

    **There were three** until #115. The `?token=` query grant was accepted so
    that a link saved before #21 kept working, and it was removed before the
    first release rather than before 1.0 as originally written, because nothing
    had shipped: there were no saved links, and nothing had generated one since
    the banner moved to `/grant#token=`. Deleting it took the access log scrub
    with it, and with that a documented dependency on where uvicorn emits its
    access line.

    The cookie is `SameSite=Lax`, not `Strict`, and the origin check still runs
    on every mutating request. Either alone would cover the cases we can think
    of, which is why there are two.

    Lax rather than Strict because Strict is withheld on a cross site TOP LEVEL
    navigation, which is exactly the phone flow this exists for: grant the
    cookie once, then later tap a Hitchrail link from a dashboard or a message
    and be answered 401 by a cookie you do hold, which a reload then fixes. Lax
    sends it on a top level GET and still withholds it from a cross site POST,
    and the mutations that matter are behind the origin check regardless.

    It is deliberately not `Secure`. Over plain HTTP on a LAN, a documented and
    supported deployment, a `Secure` cookie is never sent and the tool silently
    stops working. The cleartext exposure is stated as a limitation in the
    README, with a TLS terminating proxy as the remedy.
    """

    def __init__(self, app: ASGIApp, token: str | None) -> None:
        self.app = app
        self.token = token

    async def __call__(self, scope: Scope, receive: Receive, send: Send) -> None:
        if scope["type"] not in ("http", "websocket") or self.token is None:
            await self.app(scope, receive, send)
            return

        # The exemption, and it is a PATH test rather than a content type one.
        # `Accept: text/html` on any 401 would mean the API starts answering a
        # script with HTML the moment somebody sends a browser shaped header.
        #
        # Exact. The Origin check still runs on `POST /api/grant`,
        # because it sits inside this middleware and a grant is mutating.
        # `route_path`, not `scope["path"]`: the guard has to name the same
        # route the router will serve, and behind a sub path proxy the
        # unstripped path names a different one. That is the whole argument.
        # Sub path mounting is not a documented deployment and this does not
        # make it one; what it stops is a guard and a router disagreeing about
        # which route a request is for, which is a bug whatever the deployment.
        if (scope["type"], scope.get("method", ""), route_path(scope)) in UNAUTHENTICATED:
            await self.app(scope, receive, send)
            return

        headers = header_map(scope)

        presented = _bearer(headers.get("authorization", ""))
        if presented and token_matches(presented, self.token):
            await self.app(scope, receive, send)
            return

        # cookie_parser, not SimpleCookie: SimpleCookie discards the WHOLE jar
        # when any crumb is malformed, so one bad cookie set by another
        # application on the same host silently stops us authenticating.
        offered = cookie_parser(headers.get("cookie", "")).get(TOKEN_COOKIE)
        if offered is not None and token_matches(offered, self.token):
            await self.app(scope, receive, send)
            return

        await deny(401, "unauthorized", "a valid token is required")(scope, receive, send)


def set_token_cookie(response: Response, token: str) -> None:
    """One place, because more than one caller sets it.

    `POST /api/grant` in `server.py` sets it, and the query grant used to until
    #115. A cookie that differed between callers would be a security control
    with two definitions, which is why this stayed one function even now that
    the second carrier is gone. Not `Secure`, for the reason in
    `TokenMiddleware`'s docstring:
    over plain HTTP on a LAN, a supported deployment, a `Secure` cookie is never
    sent and the tool silently stops working.
    """
    response.set_cookie(
        TOKEN_COOKIE,
        token,
        httponly=True,
        samesite="lax",
        path="/",
        max_age=COOKIE_MAX_AGE,
    )
    # `no-store` on the one response that carries the credential (#77).
    # Hardening rather than a fix: a POST response is effectively never cached,
    # and the query grant's 303 is not either. It costs nothing and it means a
    # future carrier that IS cacheable does not have to remember this.
    response.headers["cache-control"] = "no-store"


def middleware_stack(config: Config) -> list[Middleware]:
    """Order matters, and both halves of it are asserted, not left to habit.

    Starlette applies this list as an onion: the first entry is outermost.
    Host is outermost so a rebound request never reaches anything that could
    leak whether a token is even correct. Token sits before Origin so an
    unauthenticated caller cannot enumerate the origin allowlist by watching a
    403 turn into a 401. Both are asserted in `tests/test_security_token.py`
    (#112), and `.claude/CLAUDE.md` had the order backwards until #111.
    """
    return [
        Middleware(HostAllowlistMiddleware, allowed_hosts=frozenset(config.allowed_hosts)),
        Middleware(TokenMiddleware, token=config.token),
        Middleware(OriginCheckMiddleware, allowed_origins=config.allowed_origins),
    ]
